server:
  port: 8000
spring:
  application:
    name: OneToMany
  datasource:
    url: jdbc:mysql://localhost:3306/OnetoMany
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  